//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imagen
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Comentarios { get; set; }
        public string Path { get; set; }
        public Nullable<int> esPadre { get; set; }
        public int IdArticulo { get; set; }
        public bool visible { get; set; }
    
        public virtual Articulo Articulo { get; set; }
    }
}
